/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(layer_demapper_vcvc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(69fcc27361f67395c932bbe0b0db9639)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lte/layer_demapper_vcvc.h>
// pydoc.h is automatically generated in the build directory
#include <layer_demapper_vcvc_pydoc.h>

void bind_layer_demapper_vcvc(py::module& m)
{

    using layer_demapper_vcvc    = ::gr::lte::layer_demapper_vcvc;


    py::class_<layer_demapper_vcvc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<layer_demapper_vcvc>>(m, "layer_demapper_vcvc", D(layer_demapper_vcvc))

        .def(py::init(&layer_demapper_vcvc::make),
           py::arg("N_ant"),
           py::arg("vlen"),
           py::arg("style"),
           py::arg("name") = "layer_demapper_vcvc",
           D(layer_demapper_vcvc,make)
        )
        




        
        .def("set_N_ant",&layer_demapper_vcvc::set_N_ant,       
            py::arg("N_ant"),
            D(layer_demapper_vcvc,set_N_ant)
        )


        
        .def("get_N_ant",&layer_demapper_vcvc::get_N_ant,       
            D(layer_demapper_vcvc,get_N_ant)
        )


        
        .def("set_decoding_style",&layer_demapper_vcvc::set_decoding_style,       
            py::arg("style"),
            D(layer_demapper_vcvc,set_decoding_style)
        )


        
        .def("get_decoding_style",&layer_demapper_vcvc::get_decoding_style,       
            D(layer_demapper_vcvc,get_decoding_style)
        )

        ;




}








